// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRrVzO-d7DXWa_ysy8im227ZopCIDTcQ',
    appId: '1:674821593083:web:df4624ac29bb90ac455d5e',
    messagingSenderId: '674821593083',
    projectId: 'github-eddce',
    authDomain: 'github-eddce.firebaseapp.com',
    databaseURL: 'https://github-eddce-default-rtdb.firebaseio.com',
    storageBucket: 'github-eddce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUmBPwc0iLD5hlyxLJgVlHd4K_30b8IyA',
    appId: '1:674821593083:android:522a92d79bb9aeef455d5e',
    messagingSenderId: '674821593083',
    projectId: 'github-eddce',
    databaseURL: 'https://github-eddce-default-rtdb.firebaseio.com',
    storageBucket: 'github-eddce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKriSaqnqNWBKkiDkkgeKL0C39lMzfS0c',
    appId: '1:674821593083:ios:f90b85ca8c3a667a455d5e',
    messagingSenderId: '674821593083',
    projectId: 'github-eddce',
    databaseURL: 'https://github-eddce-default-rtdb.firebaseio.com',
    storageBucket: 'github-eddce.appspot.com',
    iosBundleId: 'com.core.venturo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKriSaqnqNWBKkiDkkgeKL0C39lMzfS0c',
    appId: '1:674821593083:ios:f90b85ca8c3a667a455d5e',
    messagingSenderId: '674821593083',
    projectId: 'github-eddce',
    databaseURL: 'https://github-eddce-default-rtdb.firebaseio.com',
    storageBucket: 'github-eddce.appspot.com',
    iosBundleId: 'com.core.venturo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzRrVzO-d7DXWa_ysy8im227ZopCIDTcQ',
    appId: '1:674821593083:web:eca6c085e6050766455d5e',
    messagingSenderId: '674821593083',
    projectId: 'github-eddce',
    authDomain: 'github-eddce.firebaseapp.com',
    databaseURL: 'https://github-eddce-default-rtdb.firebaseio.com',
    storageBucket: 'github-eddce.appspot.com',
  );

}