// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNECdcqpb0o4OCKCWCvnTosVVb9ifxIUY',
    appId: '1:966405173495:web:cb016659dac9892f3f23f2',
    messagingSenderId: '966405173495',
    projectId: 'core-venturo',
    authDomain: 'core-venturo.firebaseapp.com',
    storageBucket: 'core-venturo.appspot.com',
    measurementId: 'G-97BZFPZSJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMXuFgMGBu7cZI13GAaYOLh8pVauLo3GU',
    appId: '1:966405173495:android:c19e42aeba40461c3f23f2',
    messagingSenderId: '966405173495',
    projectId: 'core-venturo',
    storageBucket: 'core-venturo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYeJVsK1G6sSoQ3uMJmq0a0MrhUdwOMps',
    appId: '1:966405173495:ios:7c6bfc8685cc23f43f23f2',
    messagingSenderId: '966405173495',
    projectId: 'core-venturo',
    storageBucket: 'core-venturo.appspot.com',
    iosBundleId: 'com.core.venturo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYeJVsK1G6sSoQ3uMJmq0a0MrhUdwOMps',
    appId: '1:966405173495:ios:7c6bfc8685cc23f43f23f2',
    messagingSenderId: '966405173495',
    projectId: 'core-venturo',
    storageBucket: 'core-venturo.appspot.com',
    iosBundleId: 'com.core.venturo',
  );
}
